### ISSUE TITLE
Unable to SSH

### ISSUE THREAD

**Issue by GeorgeChackungal** [youurayy/hyperctl#2]
Hello

I was trying to use hyperctl but is unable to ssh to the system. I always get ssh_exchange_identification: Connection closed by remote host. Nor am I able to login to the VM manually. I removed the public access to the entire user's folder and am running the PowerShell in admin mode.

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363

Any ideas?

**Comment by harishagrawal** [comment]
Hi George,
Do you have ssh keys generated in your HOME folder? I had a similar ssh problem quite some time back and found that keeping ssh keys in the default location under $env:USERPROFILE/.ssh solved the issue.

**Comment by GeorgeChackungal** [comment]
Hi @harishagrawal. Yes, I have the shh keys. The config yaml is also picking up the public keys as well.

**Comment by youurayy** [comment]
Make sure your key is in proper format (`ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub`), in the correct place (`~/.ssh/id_rsa[.pub]`), and with the correct permissions (only readable by you, not group/other or the windows equivalent).
