### ISSUE TITLE
@master: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by sojab0on** [youurayy/hyperctl#3]
Hi while trying to inint my nodes within a elevated powershell i constantly gives the following error after i created the network,and the master en 3 nodes 
@master: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)
waiting for master to init...
key_load_public: invalid format

What can i do to get it ti init and get the cluster up ad running 

I am running on Windows 10 pro with hyper-v installed the nodes and master are running as far is i can see within the hyper-v manager

**Comment by youurayy** [comment]
Make sure your key is in proper format (`ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub`), in the correct place (`~/.ssh/id_rsa[.pub]`), and with the correct permissions (only readable by you, not group/other or the windows equivalent).

**Comment by sojab0on** [comment]
i got the error away but now it keeps asking for the passphrase for the rsa file 

Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
