### ISSUE TITLE
init keeps asking for rsa passfrase 

### ISSUE THREAD

**Issue by sojab0on** [youurayy/hyperctl#4]
Hi

I got the init running without errors 

But it keeps dooing this 
Enter passphrase for key 'C:\Users\user/.ssh/id_rsa':
waiting for master to init...
Enter passphrase for key 'C:\Users\user/.ssh/id_rsa':

Is there still someting missing or mis configured

**Comment by sojab0on** [comment]
hardware specs of the mashine 
I7 860QM 
24GB ram 
1TB drive for VM storage 120GB ssd for boot 

but even after rebooting system and vms for the cluster at the master init it keeps reasking the passprase

**Comment by youurayy** [comment]
It's because you have created the key with a passphrase.  Create it without one.

Also pls always first search stackoverflow.com for these easy questions, e.g. https://www.google.com/search?q=enter+passhrase+for+key%20(site:stackoverflow.com%20OR%20site:superuser.com%20OR%20site:stackexchange.com)

**Comment by sojab0on** [comment]
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
executing on master: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 && \
      mkdir -p $HOME/.kube && \
      sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config && \
      sudo chown $(id -u):$(id -g) $HOME/.kube/config && \
      kubectl apply -f $(eval echo https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
Enter passphrase for key 'C:\Users\w510/.ssh/id_rsa':
sudo: kubeadm: command not found
master init has failed, aborting

It somehow gone further 
but gave back that

**Comment by sojab0on** [comment]
Without a passphrse set in give back persmision denied
